spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          basedir: E:\project\idea\spring-cloud-demo
          username: y369q369
          password: Yq2020.qwe
          uri: https://github.com/y369q369/spring-cloud-demo.git

server:
  port: 9007

eureka:
  client:
    serviceUrl:
      # 不开启安全认证的连接
      #      defaultZone: http://localhost:8761/eureka/
      # 开启安全认证的连接： http://${用户名}:${密码}@localhost:8761/eureka/
      defaultZone: http://admin:admin@localhost:8761/eureka/,http://admin:admin@localhost:8762/eureka/
