spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          basedir: E:\basedir     # git项目在本地的副本
          username: grassPrince   # git连接的用户名（仅限于http）
          password: Yq2020.qwe    # git连接的密码（仅限于http）
          uri: https://gitee.com/grassPrince/spring-cloud-demo.git  # git仓库地址，建议用新仓库：①每次启动会校验本地副本和服务器文件，文件内容有变化不能连接到git； ②启动后，本地文件修改，会被强制还原/更新到服务器的版本
          search-paths: config-repo # 配置文件在仓库中所在目录

#          basedir: E:\project\idea\spring-cloud-demo
#          uri: git@github.com:y369q369/spring-cloud-demo.git  # git地址使用ssh时
#          ignore-local-ssh-settings: true     # git地址使用ssh时必须
#          strict-host-key-checking: false     # git地址使用ssh时必须
#          private-key: |                      # git地址使用ssh时必须配置私钥，且私钥要以BEGIN RSA开头
#            -----BEGIN RSA PRIVATE KEY-----
#            MIIJKQIBAAKCAgEA12qs4PqvrvaUrcwuOXyoLl4vTHBOcewdgMUALU8LgjCDJzJR
#            ......
#            6ihiBlTzhGXC0TEdr4Flhgwy4oYwVEBaI5iEnI+C7oaCHb5/4d+oe1DLK4dp
#            -----END RSA PRIVATE KEY-----


server:
  port: 9007

eureka:
  client:
    serviceUrl:
      # 不开启安全认证的连接
      #      defaultZone: http://localhost:8761/eureka/
      # 开启安全认证的连接： http://${用户名}:${密码}@localhost:8761/eureka/
      defaultZone: http://admin:admin@localhost:8761/eureka/,http://admin:admin@localhost:8762/eureka/
