spring:
  application:
    name: sidecar


server:
  port: 9006

eureka:
  client:
    serviceUrl:
      # 不开启安全认证的连接
      #      defaultZone: http://localhost:8761/eureka/
      # 开启安全认证的连接： http://${用户名}:${密码}@localhost:8761/eureka/
      defaultZone: http://admin:admin@localhost:8761/eureka/,http://admin:admin@localhost:8762/eureka/


sidecar:
  # 代理第三方服务的端口，ip为localhost
  port: 9021